export const APP_PARAMS_CONFIG = {
  POSITION: "DL_CD",
  PROPERTY_INVOICE: "PROPERTY_INVOICE",
  PAYMENT_METHOD: "PAYMENT_METHOD",
  TAX_SPREAD: "TAX_SPREAD",
  VALID_PRODUCT_INVOICE: "VALID_PRODUCT_INVOICE",
  EXHIBIT_TYPE: "EXHIBIT_TYPE",
  ADJUSTMENT_TYPE: "ADJUSTMENT_TYPE",
  INVOICE_SERIAL_STATUS: "INVOICE_SERIAL_STATUS",
  SIGNATURE_TYPE: "SIGNATURE_TYPE",
  UPLOAD_TYPE: "UPLOAD_TYPE",
  USER_STATUS: "USER_STATUS",
  USER_USER_TYPE: "USER_USER_TYPE",
  USER_BUYER_TYPE: "USER_BUYER_TYPE",
  SMS_TEMP_INVOICE_CONTENT: "SMS_TEMP_INVOICE_CONTENT",
  INVOICE_CREATE_CONTENT: "INVOICE.CREATE.CONTENT",
  INVOICE_MODIFY_CONTENT: "INVOICE.MODIFY.CONTENT",
  INVOICE_REPLACE_CONTENT: "INVOICE.REPLACE.CONTENT",
  INVOICE_DELETE_CONTENT: "INVOICE.DELETE.CONTENT",
  USE_INVOICE_TEMP: "USE_INVOICE_TEMP",
  EMAIL_OPTION: "EMAIL_OPTION",
  EMAIL_SECURE_TYPE: "EMAIL_SECURE_TYPE",
  INVOICE_TEMP_SAMPLE: "INVOICE_TEMP_SAMPLE",
  INVOICE_CREATE: "INVOICE_CREATE",
  INVOICE_MODIFY: "INVOICE_MODIFY",
  INVOICE_REPLACE: "INVOICE_REPLACE",
  INVOICE_DELETE: "INVOICE_DELETE",
  EMAIL_CONTENT: "EMAIL_CONTENT",
  GENERAL: "GENERAL"
};

export const DECIMAL_PARAMS_CONFIG = {
  DECIMAL_SEPARATED_NAME: "decimal.point.space",
  THOUSANDS_SEPARATED_NAME: "decimal.point.sign.separate", // ngan cach phan nghin
  DECIMAL_SYMBOL_VALUE: 4,
  THOUSANDS_SEPARATED_SYMBOL_VALUE: 8,
  PRICE_DECIMAL_LIMIT_VALUE: 5,
  DISCOUNT_DECIMAL_LIMIT_VALUE: 7
};

export const EMAIL = {
  FIELD_SAMPLE: "FIELD_SAMPLE"
};

export const STATUS = {
  ACTIVE: 1,
  DEACTIVATE: 0
};
