export const INVOICE_DRAFT = {
  CURRENCY: "CURRENCY",
  TAX_VAT: "TAX_VAT",
  PROPERTY_INVOICE: "PROPERTY_INVOICE",
  PAYMENT_METHOD: "PAYMENT_METHOD",
  TAX_SPREAD: "TAX_SPREAD",
  VALID_PRODUCT_INVOICE: "VALID_PRODUCT_INVOICE",
  INVOICE_TYPE_CODE_INTERNAL_ORDER: "03XKNB",
  INDUSTRY_SPECIFIC_WATER_ELECTRIC: 1,
  TAX_POLICY_UNIT: 1,
  TAX_POLICY_TOTAL: 2,
  DISCOUNT_POLICY_BEFORE_TAX: 1,
  DISCOUNT_POLICY_AFTER_TAX: 2,
  DISCOUNT_POLICY_NO: 0,
  ERROR_OUT_OF_REGISTER_INVOICE: "error-2",
  ERROR_OUT_OF_CHANGE_ORDER_INVOICE: "error-4",
  ERROR_OUT_OF_RELEASE_INVOICE: "error-4",
  ERROR_NOT_ACTIVE_INVOICE: "error-3",
  ERROR_TIME_RELEASE: "error-1",
  ERROR_NOT_ACTIVE_SIGNATURE: "error-3",
  INFO_UPDATE_DATE: "3",
  INFO_UPDATE_TEXT: "1",
  INFO_UPDATE_NUMBER: "2",
  TYPE_PRODUCT_GOODS: 1,
  TYPE_PRODUCT_OTHER_FEE: 5,
  SIZE_RESPONSE_SEARCH: 20,
  MAX_LENGTH_MONEY: 15,
  MAX_LENGTH_MONEY_EXTRA: 100,
  MAX_LENGTH_DISCOUNT: 15,
  TYPE_PRODUCT_PROMOTION: 6
};

export const IMPORT_STATUS = {
  WAITING: 1,
  SUCCESS: 2,
  FAIL: 3,
  TEMPLATE_FILE_ERR: 4
};
