export const INVOICE_ANNOUNCEMENT_STATUS = {
  WAITING_APPROVAL: 1,
  APPROVED: 2,
  DIS_APPROVAL: 3,
  DRAFT: 4,
  ACTIVATE: 5,
  CAN_APPROVAL: 6,
  CANCEL: 7
};

export const FILE_ANNOUNCEMENT_TEMPLATE = {
  TEMP_RELEASE: 1,
  TEMP_32: 2,
  FORM_01: 3,
  DOCX_FILE: 4
};

export const FILE_ANNOUNCEMENT_TEMPLATE_PDF = {
  PDF_FO: 0,
  PDF_FO_EXCHANGE: 1,
  TYPE_PDF_FO: 1,
  TYPE_PDF_FO_EXCHANGE: 2
};
