export const STATUS_CODE = {
  SUCCESS: 200,
  CREATED: 201,
  AUTH: 401,
  EXIST: 409,
  BAD_REQUEST: 400,
  CONFIRM: 419,
  ARG_INVALID: 422,
  NOT_FOUND_DATA: 204,
  METHOD_NOT_ALLOWED: 405,
  PRECONDITION_REQUIRED: 428,
  GATEWAY_TIMEOUT: 504
};

export const INVOICE_ERROR_CODE = {
  INVOICE_NULL: "INVOICE_NULL",
  INVOICE_SERIAL_ACCESS_DENIED: "INVOICE_SERIAL_ACCESS_DENIED",
  INVOICE_ACTION_INVALID: "INVOICE_ACTION_INVALID",
  INVOICE_ISSUE_DATE_INVALID: "INVOICE_ISSUE_DATE_INVALID",
  INVOICE_PACKAGE_EMPTY: "INVOICE_PACKAGE_EMPTY",
  INVOICE_SIGNATURE_INVALID: "INVOICE_SIGNATURE_INVALID",
  INVOICE_INVOICE_LIST_EMPTY: "INVOICE_INVOICE_LIST_EMPTY",
  INVOICE_TAX_DECLARED: "INVOICE_TAX_DECLARED",
  INVOICE_TAX_NOT_DECLARED: "INVOICE_TAX_NOT_DECLARED",
  INVOICE_TAX_DECLARATION_EMPTY: "BAD_REQUEST_INVOICE_TAX_DECLARATION_EMPTY",
  INVOICE_VALID_INPUT_INVALID_TAX_SPREAD_ITEM:
    "INVOICE_VALID_INPUT_INVALID_TAX_SPREAD_ITEM",
  INVOICE_VALID_INPUT_INVALID_TAX_SPREAD:
    "INVOICE_VALID_INPUT_INVALID_TAX_SPREAD",
  INVOICE_VALID_INPUT_INVALID_OVER_ITEMNAME_ITEM:
    "INVOICE_VALID_INPUT_INVALID_OVER_ITEMNAME_ITEM",
  INVOICE_VALID_INPUT_INVALID_OVER_ITEMCODE_ITEM:
    "INVOICE_VALID_INPUT_INVALID_OVER_ITEMCODE_ITEM"
};
