export const STORAGE_KEYS = {
  CURRENT_USER: "CURRENT_USER",
  USER_PERMISSION_LIST: "USER_PERMISSION_LIST",
  APP_PARAMS: "APP_PARAMS",
  DECIMAL_PARAMS: "DECIMAL_PARAMS",
  APP_PARAMS_LOCAL: "APP_PARAMS_LOCAL",
  DECIMAL_PARAMS_LOCAL: "DECIMAL_PARAMS_LOCAL",
  EMAIL_LOCAL: "EMAIL_LOCAL",
  FIELD_SAMPLE_LOCAL: "FIELD_SAMPLE_LOCAL",
  SMS_CONFIG_LOCAL: "SMS_CONFIG_LOCAL",
  SMS_CONFIG_INVOICE_LOCAL: "SMS_CONFIG_INVOICE_LOCAL",
  TENANT_INFORMATION_LOCAL: "TENANT_INFORMATION_LOCAL"
};
